"""Evidence bundle generation for commercial review workflows."""

from __future__ import annotations

import csv
import html
import json
from io import StringIO
from pathlib import Path

from .models import TrustReport, portable_path
from .bom import build_bom
from .report_renderer import render_markdown
from .sarif import write_sarif
from .scanner import scan_path


def write_evidence_bundle(path: str | Path, output: str | Path, policy: str = "baseline") -> Path:
    """Write portable JSON, Markdown, HTML, risk, and remediation evidence."""

    report = scan_path(path, policy=policy)
    out_dir = Path(output)
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "skilltrust-report.json").write_text(
        json.dumps(report.to_dict(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (out_dir / "skilltrust-report.md").write_text(render_markdown(report), encoding="utf-8")
    (out_dir / "skilltrust-report.html").write_text(render_html(report), encoding="utf-8")
    write_sarif(report, out_dir / "skilltrust-report.sarif")
    (out_dir / "executive-summary.md").write_text(render_executive_summary(report), encoding="utf-8")
    (out_dir / "risk-register.csv").write_text(render_risk_register_csv(report), encoding="utf-8")
    (out_dir / "remediation-checklist.md").write_text(render_remediation_checklist(report), encoding="utf-8")
    (out_dir / "skilltrust-bom.json").write_text(
        json.dumps(build_bom(path, policy=policy), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (out_dir / "supply-chain-review.md").write_text(render_supply_chain_review(report), encoding="utf-8")
    return out_dir


def render_executive_summary(report: TrustReport) -> str:
    readiness = "not generated"
    if report.quarantine_readiness:
        readiness = f"{report.quarantine_readiness.score}/100 ({report.quarantine_readiness.status})"
    top_risks = report.findings[:5]

    lines = [
        "# SkillTrust Executive Summary",
        "",
        f"- Target: `{report.path}`",
        f"- Verdict: `{report.verdict}`",
        f"- Trust score: `{report.score}/100`",
        f"- Policy: `{report.policy}`",
        f"- Assurance level: `{report.assurance_level}`",
        f"- Quarantine readiness: `{readiness}`",
        f"- Scanned files: `{report.scanned_files}`",
        "",
        "## Decision",
        "",
        decision_text(report),
        "",
        "## Top Risks",
        "",
    ]
    if top_risks:
        lines.extend(
            f"- `{finding.severity}` `{finding.rule_id}` {finding.title} at `{finding.path}`"
            for finding in top_risks
        )
    else:
        lines.append("- No detector findings.")
    lines.extend(["", "## Evidence Files", ""])
    lines.extend(
        [
            "- `skilltrust-report.json`",
            "- `skilltrust-report.md`",
            "- `skilltrust-report.html`",
            "- `skilltrust-report.sarif`",
            "- `risk-register.csv`",
            "- `remediation-checklist.md`",
            "- `skilltrust-bom.json`",
            "- `supply-chain-review.md`",
        ]
    )
    lines.append("")
    return "\n".join(lines)


def render_supply_chain_review(report: TrustReport) -> str:
    checks = [check for check in report.control_checks if check.control_id.startswith(("SCM-", "SLSA-", "BOM-"))]
    lines = [
        "# SkillTrust Supply-Chain Review",
        "",
        f"Target: `{report.path}`",
        "",
    ]
    if checks:
        lines.extend(f"- `{check.status}` `{check.control_id}` {check.title}: {check.detail}" for check in checks)
    else:
        lines.append("- No supply-chain checks generated.")
    lines.extend(
        [
            "",
            "## Release Notes",
            "",
            "- Treat BOM and provenance outputs as review evidence, not certification.",
            "- Keep generated artifacts attached to CI runs for buyer and maintainer inspection.",
            "",
        ]
    )
    return "\n".join(lines)


def render_remediation_checklist(report: TrustReport) -> str:
    lines = [
        "# SkillTrust Remediation Checklist",
        "",
        f"Target: `{report.path}`",
        "",
    ]
    if report.remediation:
        lines.extend(f"- [ ] {item}" for item in report.remediation)
    else:
        lines.append("- [x] No remediation items generated by current detectors.")

    if report.findings:
        lines.extend(["", "## Finding Review", ""])
        lines.extend(
            f"- [ ] Review `{finding.rule_id}` at `{finding.path}` and document disposition."
            for finding in report.findings
        )

    lines.extend(
        [
            "",
            "## Release Gate",
            "",
            "- [ ] Confirm generated reports use portable paths only.",
            "- [ ] Confirm no real credentials or private infrastructure references are present.",
            "- [ ] Confirm compliance mappings are framed as review evidence, not certification.",
            "- [ ] Confirm external publishing has explicit approval.",
            "",
        ]
    )
    return "\n".join(lines)


def render_risk_register_csv(report: TrustReport) -> str:
    buffer = StringIO()
    writer = csv.writer(buffer)
    writer.writerow(["id", "severity", "title", "location", "evidence", "remediation", "status"])
    for finding in report.findings:
        location = finding.path + (f":{finding.line}" if finding.line else "")
        writer.writerow(
            [
                finding.rule_id,
                finding.severity,
                finding.title,
                location,
                finding.evidence,
                finding.remediation,
                "open",
            ]
        )
    if not report.findings:
        writer.writerow(["NONE", "info", "No detector findings", report.path, "", "", "closed"])
    return buffer.getvalue()


def render_html(report: TrustReport) -> str:
    readiness = "Not generated"
    if report.quarantine_readiness:
        readiness = f"{report.quarantine_readiness.score}/100 ({report.quarantine_readiness.status})"
    findings = "".join(
        "<tr>"
        f"<td>{html.escape(finding.rule_id)}</td>"
        f"<td>{html.escape(finding.severity)}</td>"
        f"<td>{html.escape(finding.title)}</td>"
        f"<td>{html.escape(finding.path + (':' + str(finding.line) if finding.line else ''))}</td>"
        "</tr>"
        for finding in report.findings
    ) or "<tr><td colspan=\"4\">No detector findings</td></tr>"
    controls = "".join(
        "<tr>"
        f"<td>{html.escape(check.control_id)}</td>"
        f"<td>{html.escape(check.status)}</td>"
        f"<td>{html.escape(check.title)}</td>"
        f"<td>{html.escape(check.detail)}</td>"
        "</tr>"
        for check in report.control_checks
    ) or "<tr><td colspan=\"4\">No control checks recorded</td></tr>"
    remediation = "".join(f"<li>{html.escape(item)}</li>" for item in report.remediation) or "<li>No remediation items.</li>"

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SkillTrust Evidence Report</title>
  <style>
    body {{ color: #172026; font-family: Arial, sans-serif; line-height: 1.5; margin: 32px; }}
    h1, h2 {{ color: #0f2937; }}
    .grid {{ display: grid; gap: 12px; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); }}
    .metric {{ border: 1px solid #cbd5e1; border-radius: 6px; padding: 12px; }}
    .label {{ color: #475569; font-size: 12px; text-transform: uppercase; }}
    .value {{ font-size: 22px; font-weight: 700; }}
    table {{ border-collapse: collapse; width: 100%; }}
    td, th {{ border: 1px solid #cbd5e1; padding: 8px; text-align: left; vertical-align: top; }}
    th {{ background: #eef2f7; }}
    code {{ background: #eef2f7; padding: 2px 4px; }}
    @media print {{ body {{ margin: 18mm; }} }}
  </style>
</head>
<body>
  <h1>SkillTrust Evidence Report</h1>
  <p>{html.escape(report.summary)}</p>
  <div class="grid">
    <div class="metric"><div class="label">Verdict</div><div class="value">{html.escape(report.verdict)}</div></div>
    <div class="metric"><div class="label">Trust Score</div><div class="value">{report.score}/100</div></div>
    <div class="metric"><div class="label">Policy</div><div class="value">{html.escape(report.policy)}</div></div>
    <div class="metric"><div class="label">Quarantine Readiness</div><div class="value">{html.escape(readiness)}</div></div>
  </div>
  <h2>Executive Decision</h2>
  <p>{html.escape(decision_text(report))}</p>
  <h2>Control Checks</h2>
  <table><thead><tr><th>ID</th><th>Status</th><th>Control</th><th>Detail</th></tr></thead><tbody>{controls}</tbody></table>
  <h2>Findings</h2>
  <table><thead><tr><th>ID</th><th>Severity</th><th>Finding</th><th>Location</th></tr></thead><tbody>{findings}</tbody></table>
  <h2>Remediation</h2>
  <ul>{remediation}</ul>
</body>
</html>
"""


def decision_text(report: TrustReport) -> str:
    if report.verdict == "trusted":
        return "Eligible for normal maintainer review. Continue release checks before publishing."
    if report.verdict == "review":
        return "Requires human review before installation, release, or runtime execution."
    if report.verdict == "quarantine":
        return "Keep isolated until remediation is reviewed and risk findings are resolved."
    return "Block installation or execution until the finding set is remediated and rescanned."
